name= input("Enter your name")
branch= input("Enter your branch")
gender= input("What is your gender")
collegeName= input("Enter your collegeName")
Age= int(input("Enter your Age"))
print("Name: ",name)
print("Branch: ",branch)
print("Gender: ",gender)
print("College Name: ",collegeName)
print("Age: ",Age)
